## Summary

一个程序可以使用异常来按时发生了一个错误。为了抛出一个异常，你可以使用throw语句，在关键字throws后面加上需要抛出的异常对象，这个异常对象必须是Throwable类的子类，它提供了异常发生时的具体信息。一个方法如果可能会抛出checked异常，那么必须在方法声明中包含throws子句，指定要抛出的异常类型。

一个程序可以使用try——catch-finally块来捕获异常：

* try块中包含可能会抛出异常的代码
* catch块中包含的代码，称为异常处理器，可以处理特定类型的异常，这个特定的类型由catch关键字后面的小括号中的参数类型决定
* finally块中包含的代码可以保证一定会执行，无论发生异常与否。通常会使用finally块来关闭文件，恢复资源或者做一些其他的cleanup工作。


try语句应该包括至少一个catch块或者finally块，它也可以包含多个catch块。


异常对象的类型表示被抛出的异常的类型。异常对象可以包含更多的信息，例如error message。在一个异常链中，一个异常可以指向引起它的另一个异常，另一个异常也可以指向再一个异常，等等。




















